### ISSUE TITLE
create b3dm tiles and tileset.json

### ISSUE THREAD

**Issue by Construkted-Reality** [Construkted-Reality/3DTG#1]
According to the 3d Tiles specification, (https://github.com/CesiumGS/3d-tiles) each tile is a b3dm file, and the tileset.json file specifies the location of each tile and their bounding volume. 

I have created a tool so split up a mesh into small sub-volumes. 
My tool creates multiple LoDs (Levels of detail) of the original mesh, and sub-divides each LoD into small sub-volumes.
The sub-volumes are saved as glb format.
We need to turn the sub-volumes into b3dm (using the 3D-tile-validator tool (https://github.com/CesiumGS/3d-tiles-validator/tree/2.0-tools/tools#glbtob3dm ) and create the tileset.json file.

Use this to test: https://upload.construkted.com/wl/?id=O0kAPs2HhRffUkLtZHXGGHgKOkvKTApT
This file is the output from my tool.
This file contains 7 LoDs and and for each LoD there are multiple sub-volumes stored in glb file format.
There is also a json file included `bbox_data.json` which has the bounding box volume for each file.
Take the bounding volume information from bbox_data.json and create the tileset.json that loads the 3d tiles.

**Comment by 3DGISKing** [comment]
how can I know the geometric error for each sub-volume(tile)?

**Comment by Construkted-Reality** [comment]
Good question.
I have not found a good explanation on how to calculate that value.

For now set the geometric error to 1. 

Once we figure out how to calculate it, we will change it.

**Comment by 3DGISKing** [comment]
ok

**Comment by 3DGISKing** [comment]
![image](https://user-images.githubusercontent.com/26606704/118070856-46adc300-b3d9-11eb-8cb8-b8e907094176.png)
Let me know the meaning of each element.

**Comment by Construkted-Reality** [comment]
bounding box vector values. 
Xmin,xmax,ymin,ymax,zmin,xmax

**Comment by Construkted-Reality** [comment]
Correction:
xmin,ymin,zmin,xmax,ymax,zmax

**Comment by 3DGISKing** [comment]
how can I determine a toot tile from bbox_data.json?

**Comment by Construkted-Reality** [comment]
The filenames contain that info.
For the example I provided, LOD 7 is the root tile. There are no LOD higher then that.
The filename is `RC-D01-02_LOD_07_0000.glb`

**Comment by Construkted-Reality** [comment]
### Correction:
The bounding box vector values are:
Xmin, xmax, ymin, ymax, zmin, xmax

Please ignore previous

**Comment by 3DGISKing** [comment]
yes

**Comment by 3DGISKing** [comment]
please check.

**Comment by Construkted-Reality** [comment]
Can you please provide some instructions on how to use?

**Comment by 3DGISKing** [comment]
In construktedTiler.js set importPath, exportPath, origModelName manually.
![image](https://user-images.githubusercontent.com/26606704/118695339-ad026d80-b83f-11eb-951f-c389db68c0e5.png)


then execute
```
node construktedTiler.js
```

**Comment by Construkted-Reality** [comment]
Please include all js dependencies into the test folder.
This includes all the necessary CesiumJS files

**Comment by Construkted-Reality** [comment]
Please add logic for "Geometric Error" parameter in the tileset.json as follows:
- Root tile has geometric error of 0
- The other end of the level of detail has a level of 1
- The LoD in between get a value between 0 and 1 

Example:
6 levels of detail.

level 0 has a geometric error of 1
Lod 1 geometric error 0.8
Lod 2 geometric error 0.6
Lod 3 geometric error 0.4
Lod 4 geometric error 0.2
Lod 5 geometric error 0

**I know this is not exactly how it should be done, but it's an approximation which should work for testing purposes.**
I examined several tileset.json files created with Cesium Ion, and the spread between 0 and 1 is almost linear with the level of detail.

**Comment by 3DGISKing** [comment]
ok

**Comment by 3DGISKing** [comment]
please check.
