### ISSUE TITLE
Create a local viewer for 3d tiles

### ISSUE THREAD

**Issue by Construkted-Reality** [Construkted-Reality/3DTG#2]
I need a way to locally view 3d tiles.
Easiest is to use CesiumJS as the viewer and load the local tileset.json from the local path.
Requirements:
- Load a tileset.json and diplay the 3d tiles using CesiumJS
- No software should need installing on the computer. 
- The package should be self contained. All dependancies should be included.

Please investigate how we can accomplish this.

**Comment by 3DGISKing** [comment]
please check.

**Comment by Construkted-Reality** [comment]
Please move the 3d tile viewer to the following repo
https://github.com/Construkted-Reality/3DT-Local-viewer
