### ISSUE TITLE
Missing polygons

### ISSUE THREAD

**Issue by Construkted-Reality** [Construkted-Reality/3DTG#5]
There appears to be random missing polygons in the generated chunks.

![image](https://user-images.githubusercontent.com/13057505/132048898-47d7a22f-7c8e-469b-adb4-da8ccb19398a.png)

**Comment by SergiiSharpov** [comment]
Ready for review.
The fix is placed in this commit:
https://github.com/Construkted-Reality/3DTG/commit/e923f014b990bb45cdf6c8b548878b32b7973faa
